// <auto-generated>
//   Generado por tools/generar_workflow.js desde js/constants.js. NO lo edites a mano.
// </auto-generated>
#nullable enable
namespace UniTechDesk.Core.Domain;

public static partial class WorkflowCatalog
{
    public static readonly IReadOnlyDictionary<string, StatusInfo> Statuses = new Dictionary<string, StatusInfo>(StringComparer.Ordinal)
    {
        ["OPEN"] = new StatusInfo("Abierto", new[] { "HARDWARE", "SOFTWARE" }, false),
        ["IN_REVIEW"] = new StatusInfo("En revisión", new[] { "HARDWARE", "SOFTWARE" }, false),
        ["QUOTED"] = new StatusInfo("Cotizado", new[] { "HARDWARE", "SOFTWARE" }, false),
        ["AWAITING_APPROVAL"] = new StatusInfo("Esperando aprobación", new[] { "HARDWARE", "SOFTWARE" }, false),
        ["IN_PROGRESS"] = new StatusInfo("En reparación", new[] { "HARDWARE" }, false),
        ["WAITING_PARTS"] = new StatusInfo("Esperando repuestos", new[] { "HARDWARE" }, false),
        ["IN_DEVELOPMENT"] = new StatusInfo("En desarrollo", new[] { "SOFTWARE" }, false),
        ["TESTING"] = new StatusInfo("En pruebas", new[] { "SOFTWARE" }, false),
        ["COMPLETED"] = new StatusInfo("Completado", new[] { "HARDWARE", "SOFTWARE" }, false),
        ["READY"] = new StatusInfo("Listo para entrega", new[] { "HARDWARE", "SOFTWARE" }, false),
        ["DELIVERED"] = new StatusInfo("Entregado", new[] { "HARDWARE", "SOFTWARE" }, true),
        ["CANCELLED"] = new StatusInfo("Cancelado", new[] { "HARDWARE", "SOFTWARE" }, true),
        ["UNREPAIRABLE"] = new StatusInfo("No reparable", new[] { "HARDWARE" }, false),
    };

    public static readonly IReadOnlyDictionary<string, string[]> Transitions = new Dictionary<string, string[]>(StringComparer.Ordinal)
    {
        ["OPEN"] = new[] { "IN_REVIEW", "CANCELLED" },
        ["IN_REVIEW"] = new[] { "QUOTED", "UNREPAIRABLE", "CANCELLED" },
        ["QUOTED"] = new[] { "AWAITING_APPROVAL", "IN_REVIEW", "CANCELLED" },
        ["AWAITING_APPROVAL"] = new[] { "IN_PROGRESS", "IN_DEVELOPMENT", "QUOTED", "CANCELLED" },
        ["IN_PROGRESS"] = new[] { "WAITING_PARTS", "COMPLETED", "READY", "UNREPAIRABLE", "CANCELLED" },
        ["WAITING_PARTS"] = new[] { "IN_PROGRESS", "UNREPAIRABLE", "CANCELLED" },
        ["IN_DEVELOPMENT"] = new[] { "TESTING", "COMPLETED", "CANCELLED" },
        ["TESTING"] = new[] { "IN_DEVELOPMENT", "COMPLETED", "CANCELLED" },
        ["COMPLETED"] = new[] { "READY", "DELIVERED" },
        ["READY"] = new[] { "DELIVERED" },
        ["UNREPAIRABLE"] = new[] { "READY", "CANCELLED" },
        ["DELIVERED"] = Array.Empty<string>(),
        ["CANCELLED"] = new[] { "IN_REVIEW" },
    };

    public static readonly string[] StatusOrder = new[] { "OPEN", "IN_REVIEW", "QUOTED", "AWAITING_APPROVAL", "IN_PROGRESS", "IN_DEVELOPMENT", "WAITING_PARTS", "TESTING", "UNREPAIRABLE", "COMPLETED", "READY", "DELIVERED", "CANCELLED" };

    public static readonly IReadOnlyDictionary<string, string> UserTypes = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["STUDENT"] = "Estudiante",
        ["EXTERNAL"] = "Cliente externo",
    };

    public static readonly IReadOnlyDictionary<string, string> ServiceTypes = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["HARDWARE"] = "Hardware",
        ["SOFTWARE"] = "Software",
    };

    public static readonly IReadOnlyDictionary<string, string> EquipmentTypes = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["DESKTOP"] = "Computadora de escritorio (PC)",
        ["LAPTOP"] = "Laptop / portátil",
    };

    public static readonly IReadOnlyDictionary<string, string> SoftwareKinds = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["CUSTOM_DEV"] = "Desarrollo a la medida",
        ["FIX_REVIEW"] = "Corrección o revisión de software",
        ["INSTALL_SUPPORT"] = "Instalación y soporte",
        ["CONSULTING"] = "Consultoría",
    };

    public static readonly IReadOnlyDictionary<string, string> PowersOn = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["YES"] = "Sí, enciende",
        ["NO"] = "No enciende",
        ["SOMETIMES"] = "A veces",
    };

    public static readonly IReadOnlyDictionary<string, string> Accessories = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["CHARGER"] = "Cargador / fuente",
        ["MOUSE"] = "Mouse",
        ["KEYBOARD"] = "Teclado",
        ["BAG"] = "Maletín o funda",
        ["CABLES"] = "Cables",
    };

    public static readonly IReadOnlyDictionary<string, string> Urgencies = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["LOW"] = "Baja",
        ["MEDIUM"] = "Media",
        ["HIGH"] = "Alta",
    };

    public static readonly IReadOnlyDictionary<string, string> PaymentMethods = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["CASH"] = "Efectivo",
        ["TRANSFER"] = "Transferencia",
        ["CARD"] = "Tarjeta",
    };

    public static readonly IReadOnlyDictionary<string, string> PaymentStatuses = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["NONE"] = "Sin cobro",
        ["PENDING"] = "Pendiente",
        ["PROOF_SENT"] = "En verificación",
        ["PAID"] = "Pagado",
    };

    public static readonly IReadOnlyDictionary<string, string> Currencies = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["NIO"] = "Córdobas (C$)",
        ["USD"] = "Dólares (US$)",
    };

    public static readonly IReadOnlyDictionary<string, int> UrgencyRank = new Dictionary<string, int>(StringComparer.Ordinal)
    {
        ["LOW"] = 1,
        ["MEDIUM"] = 2,
        ["HIGH"] = 3,
    };
}
