#!/usr/bin/env node
/*
 * Genera src/UniTechDesk.Core/Domain/WorkflowCatalog.g.cs a partir de js/constants.js del frontend.
 * Una sola fuente de verdad: si cambias estados, transiciones o catálogos en el front, vuelve a ejecutar:
 *     node tools/generar_workflow.js [ruta/a/constants.js]
 * y compila. La prueba WorkflowCatalogTests falla si el archivo generado quedó desactualizado respecto a
 * las reglas que aplica Workflow.cs.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const src = process.argv[2] || path.join(root, 'src/UniTechDesk.Api/wwwroot/js/constants.js');
const out = path.join(root, 'src/UniTechDesk.Core/Domain/WorkflowCatalog.g.cs');

const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(src, 'utf8'), sandbox, { filename: src });
const C = sandbox.window.UTD && sandbox.window.UTD.constants;
if (!C) { console.error('No se encontró UTD.constants en ' + src); process.exit(1); }

const s = (v) => JSON.stringify(String(v));
const arr = (a) => 'new[] { ' + a.map(s).join(', ') + ' }';
const dict = (o) => 'new Dictionary<string, string>(StringComparer.Ordinal)\n    {\n' +
  Object.keys(o).map(k => '        [' + s(k) + '] = ' + s(o[k]) + ',').join('\n') + '\n    }';

let t = '';
t += '// <auto-generated>\n';
t += '//   Generado por tools/generar_workflow.js desde js/constants.js. NO lo edites a mano.\n';
t += '// </auto-generated>\n';
t += '#nullable enable\n';
t += 'namespace UniTechDesk.Core.Domain;\n\n';
t += 'public static partial class WorkflowCatalog\n{\n';

t += '    public static readonly IReadOnlyDictionary<string, StatusInfo> Statuses = new Dictionary<string, StatusInfo>(StringComparer.Ordinal)\n    {\n';
for (const [code, st] of Object.entries(C.statuses)) {
  t += `        [${s(code)}] = new StatusInfo(${s(st.label)}, ${arr(st.services)}, ${st.final ? 'true' : 'false'}),\n`;
}
t += '    };\n\n';

t += '    public static readonly IReadOnlyDictionary<string, string[]> Transitions = new Dictionary<string, string[]>(StringComparer.Ordinal)\n    {\n';
for (const [code, to] of Object.entries(C.transitions)) t += `        [${s(code)}] = ${to.length ? arr(to) : 'Array.Empty<string>()'},\n`;
t += '    };\n\n';

t += `    public static readonly string[] StatusOrder = ${arr(C.statusOrder)};\n\n`;

const simple = {
  UserTypes: C.userTypes, ServiceTypes: C.serviceTypes, EquipmentTypes: C.equipmentTypes,
  SoftwareKinds: C.softwareKinds, PowersOn: C.powersOn, Accessories: C.accessories,
  Urgencies: C.urgencies, PaymentMethods: C.paymentMethods, PaymentStatuses: C.paymentStatuses, Currencies: C.currencies
};
for (const [name, o] of Object.entries(simple)) {
  t += `    public static readonly IReadOnlyDictionary<string, string> ${name} = ${dict(o)};\n\n`;
}
t += '    public static readonly IReadOnlyDictionary<string, int> UrgencyRank = new Dictionary<string, int>(StringComparer.Ordinal)\n    {\n';
for (const [k, v] of Object.entries(C.urgencyRank)) t += `        [${s(k)}] = ${Number(v)},\n`;
t += '    };\n}\n';

fs.writeFileSync(out, '\uFEFF' + t.replace(/\r?\n/g, '\n'), 'utf8');
console.log('Generado ' + path.relative(root, out) + ' (' + Object.keys(C.statuses).length + ' estados).');
